blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('',views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/',views.detail, name= 'detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name = 'home'),
    path('blog/', include('blog.urls')),
    path('aboutme/',views.about, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url =models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs =Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})
def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from .models import Project

def about(request):
    return render(request, 'portfolio/about.html')

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Ivan has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5><p style="color:#FF7A7A">{{ blog.date|date:'j.n.Y.' }}</p></h5>
    <p style="color:#FF7A7A">{{ blog.description|truncatechars:100 }}</p>
  </div>
</div>

{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date|date:'j.n.Y.' }}--</h2>
<div class="w-100 p-1" style="background-color: #f0ad4e;">
  <p class="text-break">
{{ blog.description|safe }}
  </p>
</div>

{% endblock %}

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base.html' %}
{% load static %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <style>
      body  {
        background-image: url("{% static "portfolio/IMG_20201014_115816-02.jpeg" %}");
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        background-color: #cccccc;
      }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/custom.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static "portfolio/images.png" %}">

    <title>Ivan's portfolio</title>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand active" href="{% url 'home' %}">Ivan Krstić<span class="sr-only">(current)</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.youtube.com/watch?v=oyrq-qzOx1U" target="_blank">Link</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container text-center">
{% block content %}{% endblock %}
</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1><p>Ivan Krstić</p></h1>
    <h3><h4>Entry level Python programmer,knowing couple of frameworks like Django and Bootstrap. Living in Nish,Serbia.</h4>
    <br>
    <br>

    {% for project in projects %}

    <h3>{{ project.title }}</h3>
    <br>
    <h2><p style="color:#FF7A7A">{{ project.description }}</p></h2>
    <br>
    <img src="{{ project.image.url }}" width=400 height=300>

    {% endfor %}
  {% endblock %}